### PR TITLE
Use query param refactoring, fix es6 kata links at the bottom of the page

### PR DESCRIPTION
**Pull request by wolframkriesing**

### CODE REVIEW

**Comment by martinandert** [comment]
Hello Wolfram, I've tried this and it works. 

Some things that seem to be unclear / broken:

* Loading the app without a kata in the url throws a `TypeError: this.kataName is undefined` because `KataUrl.fromKataName(kataName)` is called with an undefined argument in `index.js`.
* The "Reset code" button does not work, probably because of point 1.
* A query like `?kata=es6/language/destructuring/array` is turned into `?kata=es6%2Flanguage%2Fdestructuring%2Farray&storedLocally=1` after the kata is loaded. Why is that? What benefit does a user have when saving things into local storage?

**Comment by tddbin** [comment]
all great questions.
The idea here is:
1) the URLs shall become shareable (which is only partially the case this
way)
2) the locally stored modified code shall be loaded if there is some (thats
what the "storedLocally=1" parameter it for)
3) In the (hopefully near) future I want to enable storing the code in a
gist (which would be the first shot)
4) the kata name shall stay in teh URL, so you can always revert to the
origin of the kata, can share it and the "context" of what you are
currently doing is kept

I think therefore it would need to be changed, so that the url contains the
kata name and i thought of something like:
  ?kata=name&localHash=lskfuwo483
where the local hash says "there are local changes, prefer them when
loading this URL" if you share this URL noone else will have the local hash
stored in his/her localstorage, which falls back to load the original kata,
since its name is in the url
this would enable 1) sharing and 2) loading the code from localstorage and
in the future it might get extended to
  ?kata=name&localHash=lskfuwo483&remoteHash=438ueoifled
and then it would be loaded in that order:
  1) local hash available? load it, since that's what I WORKED ON
  2) remote hash available load it
  3) kata name, the final fallback

makes sense?


--
Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by martinandert** [comment]
> 3) In the (hopefully near) future I want to enable storing the code in a gist (which would be the first shot)

Can this be completely done on the client-side or will there be server-side code involved in creating gists?

> 2) remote hash available load it

Same question as above.

Jsbin and jsfiddle provide ways for a user to save her work and to clone the work of others. Are there any plans to implement such features?

**Comment by wolframkriesing** [comment]
gists can be saved purely from client, already tried it. pretty easy, they
are anonymous then ...

the gists would then be the (first) way to save a users work. attaching a
user account or alike would have to come next, would require maybe oauth
against github in order to save it in your gists, or a real login and
backend solution ... not sure i want to maintain a backend for this project
(yet)

--
Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by martinandert** [comment]
> gists can be saved purely from client, already tried it. pretty easy, they are anonymous then ...

Ah, cool. Didn't know that.

> not sure i want to maintain a backend for this project (yet)

I am cool with that. Anonymous gists seem to be a valuable option to provide save / clone functionality.

**Comment by wolframkriesing** [comment]
I am not really happy with this yet ... probably gonna dismiss this branch/PR too

**Comment by wolframkriesing** [comment]
though I still leave the branch in here

**Pull request closed without merging**
