### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by konstantinmagg**
Updated some outdated dependencies.

Started with some low hanging fruits: **eslint**, **mocha**, **watch** and **parallelshell**. Please review and test. Any comments are welcome ;)

Changes in detail:
- Updating **eslint** and its **react plugin**: New parser option *sourceType* and one violation in *index.html*
- Updating **mocha**: Changed arguments of mocha *'pre-require'* emit
- Updating **watch** and **parallelshell**: No further changes needed

I tested the updated mocha library with some simple unit tests and examples from http://es6katas.org/, worked without problems.

### CODE REVIEW

**Comment by konstantinmagg** [comment]
Had to update the node version that *Travis* uses. Hope this ain't no problem?

**Comment by wolframkriesing** [comment]
sweet

**Comment by wolframkriesing** [comment]
looks like myth doesnt play with node 6 anymore ... I will try to remove myth first

depsdiet

**Comment by wolframkriesing** [comment]
please pull in the latest master, I removed the dependency on myth, which made `npm start` not work

**Comment by wolframkriesing** [comment]
let me just do that ... getting it done :)

**Pull request closed without merging**
